image: python:3.9

stages:
  - build
  - deploy

before_script:
  - pip install sphinx

build_docs:
  stage: build
  script:
    - pip install -r requirements.txt
    - cd turbine_ug
    - sphinx-build -M html . html
  artifacts:
    paths:
      - turbine_ug/html
  only:
    - merge_requests
    - main

pages:
  stage: deploy
  script:
    - mv turbine_ug/html
  artifacts:
    paths:
      - public
  only:
    - main
