name: ci

on:
  push:
    branches-ignore:      
      - 'release-please-**'
      - 'main'
  workflow_dispatch:
    
permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  ci:
    uses: swimlane-connectors/connector-workflows/.github/workflows/ci.yml@main    
    secrets: inherit
      