name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: forces the connector to build and publish
        type: boolean
        default: false

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  connector:
    uses: swimlane-connectors/connector-workflows/.github/workflows/publish.yml@main
    with:
      publish: ${{ inputs.publish == true }}
    secrets: inherit
