schema: asset/1
name: http_basic
title: HTTP Basic Authentication
description: 'Authenticates using username and password'
inputs:
  type: object
  properties:
    url:
      title: URL
      description: A URL to the target host
      type: string
    username:
      title: Username
      description: Username
      type: string
    password:
      title: Password
      description: Password
      type: string
      format: password
    verify_ssl:
      title: Verify SSL Certificates
      description: Verify SSL certificate
      type: boolean
    http_proxy:
      title: HTTP(s) Proxy
      description: A proxy to route requests through
      type: string
  required:
    - url
    - username
    - password
meta:
  security:
    type: http
    scheme: basic
