schema: asset/1
name: oauth2_password
title: Oauth 2.0 Password
description: 'Authenticates using oauth 2.0 Password'
inputs:
  type: object
  properties:
    url:
      title: URL
      description: A URL to the target host.
      type: string
      default: https://example.service-now.com # change if it has a default cloud URL or remove if always custom.
    client_id:
      title: Client ID
      description: The client ID
      type: string
    client_secret:
      title: Client Secret
      description: The client secret.
      type: string
      format: password
    scope:
      title: Scopes
      description: Permission scopes for this action.
      type: array
      items:
        type: string
      default: [] # Add array of scopes we think are needed for the action.
    verify_ssl:
      title: Verify SSL Certificates
      description: Verify SSL certificate
      type: boolean
    http_proxy:
      title: HTTP(s) Proxy
      description: A proxy to route requests through.
      type: string
    oauth2_username:
      title: OAuth2 Username
      description: The username for authentication
      type: string
    oauth2_password:
      title: OAuth2 Password
      description: The password for authentication
      type: string
      format: password
  required:
    - url
    - client_id
    - client_secret
    - oauth2_username
    - oauth2_password
meta:
  asset_url_key: url
  security:
    token_endpoint: "oauth_token.do"
    type: oauth2
    flow: password

