schema: action/1
title: Get Attachment Metadata
name: get_attachment_metadata
description: Retrieve metadata for attachments in ServiceNow, with the ability to
  filter results using 'sysparm_query'.
inputs:
  type: object
  properties:
    parameters:
      title: Parameters
      examples:
        - sysparm_query: table_sys_id=1c741bd70b2322007518478d83673af3
      type: object
      properties:
        sysparm_query:
          title: Sysparm Query
          examples:
            - table_sys_id=1c741bd70b2322007518478d83673af3
          type: string
          description: Encoded query. Queries for the Attachment API are relative
            to the Attachments [sys_attachment] table.
      required:
        - sysparm_query
      additionalProperties: true
  required: []
  additionalProperties: true
output:
  examples:
    - status_code: 200
      response_headers:
        Server-Timing: sem_wait;dur=0, sesh_wait;dur=0
        Content-Encoding: gzip
        X-Is-Logged-In: 'true'
        X-Transaction-ID: 09ee25ec974f
        X-Total-Count: '2'
        X-Content-Type-Options: nosniff
        Pragma: no-store,no-cache
        Cache-Control: no-cache,no-store,must-revalidate,max-age=-1
        Expires: '0'
        Content-Type: application/json;charset=UTF-8
        Transfer-Encoding: chunked
        Date: Sat, 05 Nov 2022 16:24:03 GMT
        Keep-Alive: timeout=20
        Connection: keep-alive
        Server: ServiceNow
        Set-Cookie: glide_user=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT;
          Path=/; HttpOnly; SameSite=None; Secure, glide_user_session=; Max-Age=0;
          Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; HttpOnly; SameSite=None;
          Secure, glide_user_route=glide.f6d1c4085a807931391acf9b7192b09e; Max-Age=2147483647;
          Expires=Thu, 23-Nov-2090 19:38:10 GMT; Path=/; HttpOnly; SameSite=None;
          Secure, glide_session_store=4DEEE160978F111084D57E121153AF4C; Max-Age=1800;
          Expires=Sat, 05-Nov-2022 16:54:03 GMT; Path=/; HttpOnly; SameSite=None;
          Secure
        Strict-Transport-Security: max-age=63072000; includeSubDomains
      reason: OK
      json_body:
        result:
          - size_bytes: '5881'
            file_name: test
            sys_mod_count: '1'
            average_image_color: ''
            image_width: ''
            sys_updated_on: '2022-11-05 00:53:44'
            sys_tags: ''
            table_name: incident
            sys_id: 41f9dad09783111084d57e121153af94
            image_height: ''
            sys_updated_by: system
            download_link: https://dev130168.service-now.com/api/now/attachment/41f9dad09783111084d57e121153af94/file
            content_type: application/json
            sys_created_on: '2022-11-05 00:53:43'
            size_compressed: '4343'
            compressed: 'true'
            state: available
            table_sys_id: 1c741bd70b2322007518478d83673af3
            chunk_size_bytes: '700000'
            hash: 8671fa6613cd1c6e82c0e1d6b940ae0771d1d8b3f56019f8274ed501407ffc2a
            sys_created_by: admin
          - size_bytes: '5896'
            file_name: test
            sys_mod_count: '1'
            average_image_color: ''
            image_width: ''
            sys_updated_on: '2022-11-05 00:53:07'
            sys_tags: ''
            table_name: incident
            sys_id: d4d91e549783111084d57e121153afe3
            image_height: ''
            sys_updated_by: system
            download_link: https://dev130168.service-now.com/api/now/attachment/d4d91e549783111084d57e121153afe3/file
            content_type: application/json
            sys_created_on: '2022-11-05 00:53:06'
            size_compressed: '4358'
            compressed: 'true'
            state: available
            table_sys_id: 1c741bd70b2322007518478d83673af3
            chunk_size_bytes: '700000'
            hash: 11164d45817f810e70d5f84051523ef0cb12818774fc742d31cfaa158ebe747c
            sys_created_by: admin
  type: object
  properties:
    status_code:
      title: Status Code
      examples:
        - 200
      type: number
    response_headers:
      title: Response Headers
      examples:
        - Server-Timing: sem_wait;dur=0, sesh_wait;dur=0
          Content-Encoding: gzip
          X-Is-Logged-In: 'true'
          X-Transaction-ID: 09ee25ec974f
          X-Total-Count: '2'
          X-Content-Type-Options: nosniff
          Pragma: no-store,no-cache
          Cache-Control: no-cache,no-store,must-revalidate,max-age=-1
          Expires: '0'
          Content-Type: application/json;charset=UTF-8
          Transfer-Encoding: chunked
          Date: Sat, 05 Nov 2022 16:24:03 GMT
          Keep-Alive: timeout=20
          Connection: keep-alive
          Server: ServiceNow
          Set-Cookie: glide_user=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT;
            Path=/; HttpOnly; SameSite=None; Secure, glide_user_session=; Max-Age=0;
            Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; HttpOnly; SameSite=None;
            Secure, glide_user_route=glide.f6d1c4085a807931391acf9b7192b09e; Max-Age=2147483647;
            Expires=Thu, 23-Nov-2090 19:38:10 GMT; Path=/; HttpOnly; SameSite=None;
            Secure, glide_session_store=4DEEE160978F111084D57E121153AF4C; Max-Age=1800;
            Expires=Sat, 05-Nov-2022 16:54:03 GMT; Path=/; HttpOnly; SameSite=None;
            Secure
          Strict-Transport-Security: max-age=63072000; includeSubDomains
      type: object
      properties:
        Server-Timing:
          title: Server Timing
          examples:
            - sem_wait;dur=0, sesh_wait;dur=0
          type: string
        Content-Encoding:
          title: Content Encoding
          examples:
            - gzip
          type: string
        X-Is-Logged-In:
          title: X Is Logged In
          examples:
            - 'true'
          type: string
        X-Transaction-ID:
          title: X Transaction ID
          examples:
            - 09ee25ec974f
          type: string
        X-Total-Count:
          title: X Total Count
          examples:
            - '2'
          type: string
        X-Content-Type-Options:
          title: X Content Type Options
          examples:
            - nosniff
          type: string
        Pragma:
          title: Pragma
          examples:
            - no-store,no-cache
          type: string
        Cache-Control:
          title: Cache Control
          examples:
            - no-cache,no-store,must-revalidate,max-age=-1
          type: string
        Expires:
          title: Expires
          examples:
            - '0'
          type: string
        Content-Type:
          title: Content Type
          examples:
            - application/json;charset=UTF-8
          type: string
        Transfer-Encoding:
          title: Transfer Encoding
          examples:
            - chunked
          type: string
        Date:
          title: Date
          examples:
            - Sat, 05 Nov 2022 16:24:03 GMT
          type: string
        Keep-Alive:
          title: Keep Alive
          examples:
            - timeout=20
          type: string
        Connection:
          title: Connection
          examples:
            - keep-alive
          type: string
        Server:
          title: Server
          examples:
            - ServiceNow
          type: string
        Set-Cookie:
          title: Set Cookie
          examples:
            - glide_user=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/;
              HttpOnly; SameSite=None; Secure, glide_user_session=; Max-Age=0; Expires=Thu,
              01-Jan-1970 00:00:10 GMT; Path=/; HttpOnly; SameSite=None; Secure, glide_user_route=glide.f6d1c4085a807931391acf9b7192b09e;
              Max-Age=2147483647; Expires=Thu, 23-Nov-2090 19:38:10 GMT; Path=/; HttpOnly;
              SameSite=None; Secure, glide_session_store=4DEEE160978F111084D57E121153AF4C;
              Max-Age=1800; Expires=Sat, 05-Nov-2022 16:54:03 GMT; Path=/; HttpOnly;
              SameSite=None; Secure
          type: string
        Strict-Transport-Security:
          title: Strict Transport Security
          examples:
            - max-age=63072000; includeSubDomains
          type: string
      required: []
      additionalProperties: true
    reason:
      title: Reason
      examples:
        - OK
      type: string
    json_body:
      title: JSON Body
      examples:
        - result:
            - size_bytes: '5881'
              file_name: test
              sys_mod_count: '1'
              average_image_color: ''
              image_width: ''
              sys_updated_on: '2022-11-05 00:53:44'
              sys_tags: ''
              table_name: incident
              sys_id: 41f9dad09783111084d57e121153af94
              image_height: ''
              sys_updated_by: system
              download_link: https://dev130168.service-now.com/api/now/attachment/41f9dad09783111084d57e121153af94/file
              content_type: application/json
              sys_created_on: '2022-11-05 00:53:43'
              size_compressed: '4343'
              compressed: 'true'
              state: available
              table_sys_id: 1c741bd70b2322007518478d83673af3
              chunk_size_bytes: '700000'
              hash: 8671fa6613cd1c6e82c0e1d6b940ae0771d1d8b3f56019f8274ed501407ffc2a
              sys_created_by: admin
            - size_bytes: '5896'
              file_name: test
              sys_mod_count: '1'
              average_image_color: ''
              image_width: ''
              sys_updated_on: '2022-11-05 00:53:07'
              sys_tags: ''
              table_name: incident
              sys_id: d4d91e549783111084d57e121153afe3
              image_height: ''
              sys_updated_by: system
              download_link: https://dev130168.service-now.com/api/now/attachment/d4d91e549783111084d57e121153afe3/file
              content_type: application/json
              sys_created_on: '2022-11-05 00:53:06'
              size_compressed: '4358'
              compressed: 'true'
              state: available
              table_sys_id: 1c741bd70b2322007518478d83673af3
              chunk_size_bytes: '700000'
              hash: 11164d45817f810e70d5f84051523ef0cb12818774fc742d31cfaa158ebe747c
              sys_created_by: admin
      type: object
      properties:
        result:
          title: Result
          examples:
            - - size_bytes: '5881'
                file_name: test
                sys_mod_count: '1'
                average_image_color: ''
                image_width: ''
                sys_updated_on: '2022-11-05 00:53:44'
                sys_tags: ''
                table_name: incident
                sys_id: 41f9dad09783111084d57e121153af94
                image_height: ''
                sys_updated_by: system
                download_link: https://dev130168.service-now.com/api/now/attachment/41f9dad09783111084d57e121153af94/file
                content_type: application/json
                sys_created_on: '2022-11-05 00:53:43'
                size_compressed: '4343'
                compressed: 'true'
                state: available
                table_sys_id: 1c741bd70b2322007518478d83673af3
                chunk_size_bytes: '700000'
                hash: 8671fa6613cd1c6e82c0e1d6b940ae0771d1d8b3f56019f8274ed501407ffc2a
                sys_created_by: admin
              - size_bytes: '5896'
                file_name: test
                sys_mod_count: '1'
                average_image_color: ''
                image_width: ''
                sys_updated_on: '2022-11-05 00:53:07'
                sys_tags: ''
                table_name: incident
                sys_id: d4d91e549783111084d57e121153afe3
                image_height: ''
                sys_updated_by: system
                download_link: https://dev130168.service-now.com/api/now/attachment/d4d91e549783111084d57e121153afe3/file
                content_type: application/json
                sys_created_on: '2022-11-05 00:53:06'
                size_compressed: '4358'
                compressed: 'true'
                state: available
                table_sys_id: 1c741bd70b2322007518478d83673af3
                chunk_size_bytes: '700000'
                hash: 11164d45817f810e70d5f84051523ef0cb12818774fc742d31cfaa158ebe747c
                sys_created_by: admin
          type: array
      required: []
      additionalProperties: true
  required: []
  additionalProperties: true
meta:
  endpoint: api/now/attachment
  method: GET
