name: Convert and Push Docs

on:
  push:
    branches:
      - main

jobs:
  convert-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run conversion script
        run: python scripts/convert_docs.py

      - name: Push to Techpubs Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
          git clone https://github.com/swimlane/techpubs-knowledgecenter.git temp-docs
          mkdir -p temp-docs/docs
          cp -r output/docs/* temp-docs/docs/
      
          cd temp-docs
          git add .
          git commit -m "Automated doc update from tesing_rtd" || echo "Nothing to commit"
          git push origin main
        env:
         GITHUB_TOKEN: ${{ secrets.TECHPUBS_TOKEN }}


